postcard/Models/BlobContainer.cs
using System;
namespace postcard.Models
{
	public class BlobContainer
	{
        public string URL { get; set; }
        public string name { get; set; }
    }
}

postcard/Models/Capas.cs
using System;
namespace postcard.Models
{
	public class Capas
	{
		public int id { get; set; }
		public string uf { get; set; }
		public string estado { get; set; }
		public string musica { get; set; }
		public string youtube { get; set; }
		public string imagem { get; set; }

		public string URLimg { get; set; }

		public string error { get; set; }
	}
}

postcard/Models/ErrorViewModel.cs
namespace postcard.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

postcard/Models/Estado.cs
using System;
namespace postcard.Models
{
	public class Estado
	{
		public string estado { get; set; }

		public List<PostCards> listpostcards { get; set; }

        public string hostip { get; set; }
    }
}

postcard/Models/FeatureToggle.cs
using System;
using Azure;
using Azure.Data.Tables;

namespace postcard.Models
{
	public class FeatureToggle : ITableEntity
    {
		public string PartitionKey { get; set; }
		public string RowKey { get; set; }
		public string ativo { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }
    }
}

postcard/Models/Home.cs
using System;
namespace postcard.Models
{
	public class Home
	{
		public string hostip { get; set; }

		public List<Capas> listcapas { get; set; }
	}
}

postcard/Models/PostCards.cs
using System;
namespace postcard.Models
{
	public class PostCards
	{
		public int id { get; set; }
		public int id_uf { get; set; }
		public string uf { get; set; }
		public string cidade { get; set; }
		public string card { get; set; }
		public string descricao { get; set; }

		public string URLimg { get; set; }
	}
}

postcard/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using postcard.Models;
using Azure.Storage.Blobs;
using Azure.Storage.Queues.Models;
using System.Net;
using System.Net.Sockets;
using Microsoft.Extensions.Hosting;
using System.Reflection;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace postcard.Controllers
{
    public class CardsController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;

        public CardsController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _configuration = configuration;
            _logger = logger;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index(int _iduf, string _estado)
        {
            var model = new Estado();
            var modelcards = new List<PostCards>();

            var hostname = Dns.GetHostEntry(Dns.GetHostName());

            foreach (var ip in hostname.AddressList)
            {
                if (ip.AddressFamily == AddressFamily.InterNetwork)
                {
                    model.hostip = ip.ToString();
                }
            }

            modelcards = await new SQLUtility().getcards("select postcards.id, postcards.id_uf, capas.uf, postcards.cidade, postcards.card, postcards.descricao from postcards INNER JOIN capas on capas.id = postcards.id_uf WHERE capas.Id = " + _iduf.ToString(), _configuration);

            model.estado = _estado;
            model.listpostcards = modelcards;

            return View(model);
        }

        public async Task<ActionResult> DownloadFile(string cardname, string filename, string URLimg, string hostip)
        {
            Stream stream = await new StorageUtility().getstreamtodownload(_configuration, cardname);

            string jsonqueueMessage = @"{""host"" : """ + hostip + @""",""arquivo"" : """ + filename + @""",""url"" : """ + URLimg +@"""}";

            SendMessageDownload(jsonqueueMessage);
            return File(stream, "application /jpeg", filename);
        }

        public ActionResult SendMessageDownload(string queueMessage)
        {
            new StorageUtility().SendMessageToQueue(_configuration, queueMessage.ToString());
            return Ok();
        }
    }
}

postcard/Controllers/HomeController.cs
using System.Diagnostics;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using postcard.Models;
using System.Net.Sockets;
using System.Configuration;
using Microsoft.Extensions.Configuration;

namespace postcard.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IConfiguration _configuration;

    public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
    {
        _configuration = configuration;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        var model = new Home();
        var modelcapa = new List<Capas>();
        var hostname = Dns.GetHostEntry(Dns.GetHostName());

        foreach (var ip in hostname.AddressList)
        {
            if (ip.AddressFamily == AddressFamily.InterNetwork)
            {
                model.hostip = ip.ToString();
            }
        }
        
        modelcapa = await new SQLUtility().getcapas("SELECT Id, uf, estado, musica, youtube, imagem FROM capas", _configuration);

        model.listcapas = modelcapa;

        return View(model);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

postcard/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using postcard.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace postcard.Controllers
{
    public class UploadController : Controller
    {
        private readonly IConfiguration _configuration;

        public UploadController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var model = new Home();

            var hostname = Dns.GetHostEntry(Dns.GetHostName());

            foreach (var ip in hostname.AddressList)
            {
                if (ip.AddressFamily == AddressFamily.InterNetwork)
                {
                    model.hostip = ip.ToString();
                }
            }

            return View(model);
        }

        public async Task<ActionResult> UploadFile(List<IFormFile> files)
        {
            try
            {
                long size = files.Sum(f => f.Length);

                var filePaths = new List<string>();
                foreach (var formFile in files)
                {
                    if (formFile.Length > 0)
                    {
                        var filePath = Path.GetTempFileName();
                        var filename = formFile.FileName;
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await formFile.CopyToAsync(stream);
                            new StorageUtility().uploadfiletoshare(_configuration, filename, stream);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

postcard/Views/Cards/Index.cshtml
@model postcard.Models.Estado
<div class="container text-center">
    <h1>@Model.estado</h1>
    <div class="row">
        @foreach (var item in Model.listpostcards)
        {
            <div class="col">
                <div class="card cardcapa">
                    <img src="@item.URLimg" class="logopostcard" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@item.cidade - @item.descricao</h5>
                        <p class="card-text"></p>
                        <a href='@Url.Action("DownloadFile", "Cards", new { cardname = "cards/"+@item.uf+"/"+@item.card, filename = @item.card, URLimg = @item.URLimg, hostip = @Model.hostip })' class="btn btn-primary">Download</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

postcard/Views/Home/Index.cshtml
@model postcard.Models.Home
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <a class="" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="images/cloud_treinamentos_-_escolhida_-_1.png" /></a>
    <h5>Az DevOps- Host: @Model.hostip</h5>
</div>
<div class="container text-center">
        @Html.Partial("_Capas.cshtml")
</div>

postcard/Views/Home/_Capas.cshtml
@model postcard.Models.Home
<div class="row">
    @foreach (var item in Model.listcapas)
    {
        <div class="col">
            <div class="card cardcapa">
                <img src="@item.URLimg" class="logopostcard" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@item.estado</h5>
                    <p class="card-text">@item.musica<a href="@item.youtube" target="_blank">mais</a></p>
                    <a href='@Url.Action("Index", "Cards", new { _iduf = item.id, _estado = item.estado })' class="btn btn-primary">Ver cartões</a>
                </div>   
            </div>
        </div>
     }
 </div>

postcard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cloud Treinamentos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/gamecatalog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><img class="singlelogo" src="../../images/logo.jpeg" alt="Card image cap"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://stressmypc.br.uptodown.com/windows/download" target="_blank">Stress My PC (Windows)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://github.com/augroberto/FORMACAO-AZURE/blob/main/Aula%202/Labs/0%20-%20Stress%20VM.txt" target="_blank">Stress My PC (Linux)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href='@Url.Action("Index", "Upload")'>Upload File</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - Cloud Treinamentos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

postcard/Views/Upload/Index.cshtml
@model postcard.Models.Home
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <a class="" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="images/cloud_treinamentos_-_escolhida_-_1.png" /></a>
    <h5>Host: @Model.hostip</h5>
</div>
<div class="container text-center">
    <div class="row">
        <div class="col">
            <form method="post" enctype="multipart/form-data" asp-controller="Upload" asp-action="UploadFile">
                <input class="form-control uploadform" type="file" name="files" multiple />
                 <input type="submit" value="Upload" class="btn btn-primary"/>
            </form>
        </div>
    </div>
</div>